#------------------------------------------------------
#
# Possible States: "EXCELLENT", "GOOD", "DEGRADED", "CRITICAL", "DISABLED"
# Possible types: "zenoh", "gstreamer", "ros_gstreamer"
# ------------------------------------------------------

global:
  target_ip: 192.168.178.123 
  ros_domain: 0

streams:
  color_camera_info:
    type: zenoh
    topic: /camera/camera/color/camera_info
    frequency: 5
    priority: 1
    express: true
    msg_type: sensor_msgs/CameraInfo
    allowed_in_state: [ALL, EXCELLENT]
  network_information:
    type: zenoh
    topic: /network_state
    priority: 4
    msg_type: sensor_msgs/CameraInfo
    allowed_in_state: [ALL]
  depth_camera_info:
    type: zenoh
    topic: /camera/camera/depth/camera_info
    msg_type: sensor_msgs/CameraInfo
    allowed_in_state: [ALL]
  logitech_webcam:
    type: gstreamer
    device: /dev/video6
    port: 5005
    width: 640
    height: 480
    min_bitrate: 1000
    max_bitrate: 4000
    allowed_in_state: [EXCELLENT, GOOD]
  camera_stream1:
    type: ros2_gstreamer
    topic: /camera/camera/color/image_raw
    port: 5006
    min_bitrate: 1000
    max_bitrate: 4000
    allowed_in_state: [EXCELLENT, ALL]  
  thermal_cam:
    type: thermal
    port: 5008 # Port where gstreamer sends the video to
    width: 320
    height: 240
    normalize: true #OPTIONAL: (true|false) Normalize the frame values to use the full contrast range -> DEFAULT = true
    normalize-frame-count: 33 #OPTIONAL: (int) How many frames to use for normalization -> DEFAULT = 32
    skip-invalid-frames: true #OPTIONAL: (true|false) If true, send only valid frames, if false, send all, which includes calibration frames where the shutter is closed and opens. -> DEFAULT = true
    min_bitrate: 1000
    max_bitrate: 4000
    allowed_in_state: [ALL, EXCELLENT]

